version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: media-metadata-project
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_DB: your_database
  #     POSTGRES_USER: your_username
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #   volumes:
  #     - .:/app
  #   command: ["python", "example-1.py"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

